version: "3.6"

services:
  pro-deputy-hub:
    build:
      context: ..
      dockerfile: ./docker/sirius-pro-deputy-hub/Dockerfile
    ports: ["8888:1234"]
    environment:
      SIRIUS_URL: http://docker.for.mac.localhost:8080
      SIRIUS_PUBLIC_URL: http://localhost:8080
      PREFIX: /supervision/deputies/professional